# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# on:
#   push:
#     paths:
#       - '**/integrations/*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test || true
    - uses: mikepenz/xray-action@v0.9.4
      with:
        username: ${{ secrets.client_id }}
        password: ${{ secrets.client_secret }}
        testFormat: "junit"
        testPaths: "junit.xml"
       # testExecKey: "XRAYD-14"
        testPlanKey: "XRAYD-138"
        continueOnImportError: true
        projectKey: "XRAYD"
#     - name: API Automation Result
#       uses: ivanklee86/xunit-slack-reporter@v1.4.0
#       with:
# #         EXIT_CODE_FROM_REPORT: "True"
#         SLACK_CHANNEL: C02TFU4Q4H2
#         SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
#         XUNIT_PATH: /github/workspace/junit.xml
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: fortresstech.net
        # Required mail server port:
        server_port: 443
#         # Optional (recommended): mail server username:
#         username: ${{secrets.MAIL_USERNAME}}
#         # Optional (recommended) mail server password:
#         password: ${{secrets.MAIL_PASSWORD}}
#         # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: palasgarov@fortresstech.net
        # Required sender full name (address can be skipped):
        from: Luke Skywalker # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        html_body: file://README.html
        # Optional carbon copy recipients:
#         cc: kyloren@example.com,leia@example.com
#         # Optional blind carbon copy recipients:
#         bcc: r2d2@example.com,hansolo@example.com
#         # Optional recipient of the email response:
#         reply_to: luke@example.com
#         # Optional Message ID this message is replying to:
#         in_reply_to: <random-luke@example.com>
#         # Optional unsigned/invalid certificates allowance:
#         ignore_cert: true
#         # Optional converting Markdown to HTML (set content_type to text/html too):
#         convert_markdown: true
#         # Optional attachments:
#         attachments: attachments.zip,git.diff,./dist/static/*.js
#         # Optional priority: 'high', 'normal' (default) or 'low'
        priority: low
